image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/Ataraxxia/godin
  PACKAGE: godin-server

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - export BUILDVERSION=$(cat VERSION.txt)
    - export BUILDTIME=$(date +"%F_%T")
    - go build -race -ldflags "-extldflags '-static' -X 'main.BuildTime=$BUILDTIME' -X 'main.BuildVersion=$BUILDVERSION'" -o $CI_PROJECT_DIR/godin
    - mkdir -p $PACKAGE/usr/sbin
    - mkdir -p $PACKAGE/etc/godin
    - mkdir -p $PACKAGE/DEBIAN
    - cp -R debian/* $PACKAGE/DEBIAN/
    - cp godin $PACKAGE/usr/sbin/
    - cp settings.json.example $PACKAGE/etc/godin/
    - dpkg-deb --build --root-owner-group $PACKAGE
    - mkdir -p releases
    - mv $PACKAGE.deb releases/${PACKAGE}_${BUILDVERSION}_${BUILDTIME}-amd64.deb

  artifacts:
    paths:
      - releases/*.deb
